### ISSUE TITLE
Webinar Las matemáticas detrás del performance testing

### ISSUE THREAD

**Issue by MrsDaehin** [NorthemQuality/community-activities#1]
# Propuesta de Actividad

## Título

> Las Matemáticas detrás del performance testing
## Descripción

> Cómo modelar un test de performance? Cómo analizar los resultados? Hay una gran carga de matemáticas, y  mucho sentido común también. En este webinar hablaremos de las estrategias de test y de las matemáticas que hay detrás de esa metodología. 

## Nivel

> Estadística básica. Hablaremos de percentiles, medias, modas, desviación típica, poblaciones, estadísticos y distribuciones. 

## Información adicional

> Conexión a internet y jmeter instalado

## Sobre mí

> Natural de Avilés, estudié Matemática aplicada y Computación en la Universidad de Oviedo. Me marché como muchos otros en 2003 a Barcelona donde desarrollé mi actividad profesional entre otras en Infojobs y Telefónica I+D. Desde 2019 trabajo para Lidl Internacional SCRM como performance Engineer. Me dedico a la divulgación y a animar a la integración de la mujer en el mundo STEM dentro de una organización llamada Girls in Tech. Me podéis encontrar en redes sociales y de juego como MrsDaehin. 

## Enlace al video

https://www.youtube.com/watch?v=f1BytsY1KaM

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/NorthemQuality/community-documentation/blob/master/CODIGO_CONDUCTA.md
[terms]: Añadir términos

**Comment by morvader** [comment]
Gracias por la propuesta @MrsDaehin .

Tal y como habíamos comentado, fijamos el día **8 de Marzo** para esta charla.

Muchas gracias y happy testing!
@aaguila
