### ISSUE TITLE
Progressive Delivery in Kubernetes

### ISSUE THREAD

**Issue by aaguila** [NorthemQuality/community-activities#12]
# Propuesta de Actividad

## Título

> Progressive Delivery in Kubernetes

## Descripción

Progressive Delivery es un término que incluye metodologías tales como actualizaciones progresivas, despliegues de blue-green o canary releases. Lo que es común a todos ellos es que la monitorización y las métricas se utilizan para evaluar si la nueva versión es "segura" o si es necesario hacer roll-back. Estas técnicas se utilizan en empresas como Facebook para desplegar nuevas versiones gradualmente. Pero buenas noticias! no necesitas ser Facebook para aprovecharte de ello.

Enseñaremos cómo crear un pipeline de Progressive Delivery totalmente automatizado con despliegues y roll-backs en Kubernetes usando Jenkins X, una plataforma de código abierto para CI/CD nativo de la nube en Kubernetes, y Flagger, un proyecto que utiliza Istio y Prometheus para automatizar Canary rollouts and rollbacks

## Enlace al video

> https://www.youtube.com/watch?v=u7Z1V_NcmPY

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/NorthemQuality/community-documentation/blob/master/CODIGO_CONDUCTA.md
[terms]: https://github.com/NorthemQuality/community-activities/blob/master/TERMS.md

**Comment by morvader** [comment]
Charla realizada
