### ISSUE TITLE
Lo nuevo de Katalon Studio para Testing Automatizado 

### ISSUE THREAD

**Issue by aaguila** [NorthemQuality/community-activities#17]
# Propuesta de Actividad

## Título

> Lo nuevo de Katalon Studio para Testing Automatizado 

## Descripción

> En este webinar les mostraremos cómo realizar testing automatizado con la herramienta Katalon Studio. Veremos diferentes características y beneficios de la herramienta, así como también las funcionalidades que se incorporaron en su última versión.

Crearemos scripts automatizados a nivel de interfaz de usuario y mostraremos cómo ejecutarlas de forma rápida en distintos navegadores.

## Sobre nosotros

Gastón Marichal

Licenciado en Sistema de la Universidad ORT Uruguay. Es responsable de coordinar las actividades de aseguramiento de la calidad en proyectos de modalidad Software Factory. Cuenta con más de 6 años de experiencia realizando actividades de testing funcional, automatización, performance y seguridad. Ha dictado cursos de Testing para distintas organizaciones y fundaciones a nivel regional. Forma parte del equipo de testing de QAlified, la unidad de negocio de Testing y Aseguramiento de la Calidad de GeneXus Consulting.

Carolina Rodriguez

Estudiante de Ingeniería en Sistemas en la Universidad Católica. Ha participado en proyectos de distintos rubros de la industria en modalidad Software Factory, cuenta con experiencia en testing funcional y automatización de pruebas. Forma parte del equipo de testing de QAlified, la unidad de negocio de Testing y Aseguramiento de la Calidad de GeneXus Consulting.

## Enlace al video

> https://www.youtube.com/watch?v=0HxPt4xAj-8

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/NorthemQuality/community-documentation/blob/master/CODIGO_CONDUCTA.md
[terms]: https://github.com/NorthemQuality/community-activities/blob/master/TERMS.md

**Comment by morvader** [comment]
Terminada
