### ISSUE TITLE
¡Se me ha roto la accesibilidad!

### ISSUE THREAD

**Issue by aaguila** [NorthemQuality/community-activities#19]
# Propuesta de Actividad

## Título

> ¡Se me ha roto la accesibilidad!

## Descripción

> ¡Ya estáis listos para sacar la versión 2.0 de vuestro producto estrella! En la versión 1.0 os preocupasteis muchísimo por la accesibilidad, y hasta contratasteis a una consultora que os ayudó a que fuera 100% accesible.
Lanzáis la versión... y de repente, os empiezan a llegar tweets de un montón de usuarios cabreados diciéndoos que lo que antes era accesible ya no lo es. Lo primero que pensáis: ¡maldito twitter! Y lo segundo: ¿qué ha pasado? ¿cómo ha podido producirse semejante regresión?
En esta charla os contaré cómo mantener vuestro sitio web accesible a lo largo del tiempo, sin tener que estar realizando constantes tests manuales cada vez que se hace un cambio en la interfaz. Aprenderemos a crear tests automatizados (analizando páginas completas o componentes aislados), e incluso crearemos tests utilizando lectores de pantalla, todo  de manera totalmente automática, y los incluiremos como parte del flujo de integración continua de vuestro software.
¡Gracias a esta charla, podrás conseguir que la accesibilidad sea un pilar fundamental de tu producto, impidiendo que cualquier problema de accesibilidad sea publicado en producción. ¡Ahora tus pull requests también tendrán en cuenta los tests de accesibilidad como un parámetro de calidad adicional antes de ser aprobados!
¡Que el esfuerzo invertido en accesibilidad no se lo lleve el viento de la entropía! 

## Enlace al video

> https://www.youtube.com/watch?v=w5P156AqPV0

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/NorthemQuality/community-documentation/blob/master/CODIGO_CONDUCTA.md
[terms]: https://github.com/NorthemQuality/community-activities/blob/master/TERMS.md

**Comment by morvader** [comment]
Terminada
