### ISSUE TITLE
Evolución del QA en entornos ágiles

### ISSUE THREAD

**Issue by aaguila** [NorthemQuality/community-activities#20]
# Propuesta de Actividad

## Título

> Evolución del QA en entornos ágiles

## Descripción

> En esta mesa redonda hablaremos de la evolución del QA en entornos ágiles.

## Enlace al video

> https://www.youtube.com/watch?v=TWqLeUosH_o

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/NorthemQuality/community-documentation/blob/master/CODIGO_CONDUCTA.md
[terms]: https://github.com/NorthemQuality/community-activities/blob/master/TERMS.md

**Comment by morvader** [comment]
Terminada
