### ISSUE TITLE
Define tu pirámide de test al más puro estilo retrospective

### ISSUE THREAD

**Issue by jaalvarezvi** [NorthemQuality/community-activities#21]
# Propuesta de Actividad

## Título

> Define tu pirámide de test al más puro estilo retrospective

## Descripción

> Recientemente hemos redefinido e implementado la estrategia de testing del sistema más crítico de nuestra empresa (procesador de pagos on line, más de 500k payments diarios). Durante este proceso hemos tenido que replantearnos muchas cosas, conceptos e ideas preconcebidas que nos gustaría compartir con la comunidad, pero especialmente, el proceso que hemos seguido para definir nuestra estrategia que entendemos puede seguir cualquier equipo al más puro estilo retrospective, aunque salvando las diferencias, con ello queremos decir que se puede hacer un ejercicio con un hilo conductor que en conjunto con la aportación de ideas y opiniones de los integrantes del equipo te pueden llevar a definir tu pirámide de tests. Es solo una forma de hacerlo, puede parecer poco, pero en realidad para cualquier equipo/persona que no tenga claro cómo abordar este tema es realmente útil.

## Nivel

> Creo que los conocimientos necesarios son básicos y conceptuales, todos relacionados con calidad software como tipos de test, aunque en realidad la charla es en sí misma auto explicativa, así que está orientada para todos los públicos con interés en calidad software.

## Información adicional

> A ser una charla y no un taller no es necesario más que conexión a internet y curiosidad.

## Sobre mí

> Soy QA Engineer en Payvision (www.payvision.com), una Fintech cuya principal actividad es el procesamiento de pagos Online, recientemente adquirida en su totalidad por ING. He trabajado como QA en empresas de diferente tamaño e industria. Más de mí: https://www.linkedin.com/in/julianalvarezvillanueva/

## Enlace al video

> https://www.youtube.com/watch?v=_TqSdgdJE3o

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/NorthemQuality/community-documentation/blob/master/CODIGO_CONDUCTA.md
[terms]: https://github.com/NorthemQuality/community-activities/blob/master/TERMS.md

**Comment by morvader** [comment]
Muchas gracias por la propuesta @jaalvarezvi . La verdad es que tiene muy buena pinta y te agradecemos enormemente que quieras compartirlo con la comunidad.

Solemos plantear sesiones de unos 40-50 minutos de exposición y dejando al final tiempo para preguntas. ¿Te encajan estos tiempos y formato?

Por otro lado, ¿qué disponibilidad tendrías de fechas?.

**Comment by jaalvarezvi** [comment]
Gracias por la pronta respuesta @morvader !
Me alegro de que haya despertado el interés. Respecto a la duración y formato me parece perfecto. Respecto a la disponibilidad, no sé con cuánto tiempo de antelación se empieza a preparar el webinar para dar más visibilidad, etc... A mí me viene bien a partir de la semana del 10 de mayo, cualquier día de la semana, y respecto a la hora, si es con tiempo me puedo adaptar.

**Comment by morvader** [comment]
Hola @jaalvarezvi .

Tendrías disponibilidad para el mes de Junio?. Solemos hacer los eventos los jueves de tarde. Habitualmente de 19 a 20. Pero podemos adaptarnos.

Ya nos dices y muchas gracias! :)

**Comment by morvader** [comment]
Hola de nuevo @jaalvarezvi . Seguirías estando interesado en dar la esta charla?

**Comment by jaalvarezvi** [comment]
@morvader Hola! Disculpa que al final no contesté. Si, sigo interesado, te importaría si lo planificamos para finales de Junio?

**Comment by aaguila** [comment]
Buenas @jaalvarezvi ! ¿Cómo tendrías la primera semana de Julio?

**Comment by jaalvarezvi** [comment]
@morvader Hola, me viene bien. Sería el jueves 9 de julio?

**Comment by morvader** [comment]
Celebrada
