### ISSUE TITLE
Testing Exploratorio y Mind Maps

### ISSUE THREAD

**Issue by cbadell** [NorthemQuality/community-activities#7]
# Propuesta de Actividad

## Título

Testing Exploratorio y Mind Maps

## Descripción

Claudia nos contará brevemente qué es el testing exploratorio, para luego contarnos cómo en el contexto de un equipo interdisciplinario totalmente dedicado a desarrollar un producto, el uso de mind maps les ha permitido compartir y reutilizar a nivel de equipo el conocimiento adquirido durante las pruebas exploratorias. Claudia también nos contará brevemente cómo diseñan los mind maps en el equipo de forma tal de que puedan ser utilizados y extendidos independientemente de quién los haya creado, como también algunas lecciones aprendidas durante este proceso. Al final del webinar, Claudia nos compartirá algunas recomendaciones para comenzar a aplicar un enfoque de pruebas exploratorias basado en mind maps.

## Nivel

Todos los niveles.

## Información adicional

n/a

## Sobre mí

Claudia Badell es Ingeniera en Computación y actualmente se desempeña como Senior Quality Engineer. Cuenta con más de 13 años de experiencia en el área de testing y participa en forma activa en la comunidad de testing en Uruguay, donde co-organiza meetups y [TestingUy](https://testinguy.org/), una de las conferencias de testing más importantes en América Latina. Claudia ha sido oradora en conferencias internacionales como Agile Testing Days USA, expo:QA, Next Generation Testing Conference, TestingUy, VLCTesting y World Conference for Software Quality. También ha dado webinars en conferencias y plataformas virtuales como Agile Testers Conference y OnlineTestConf. Junto con Joanna Arnaiz crearon y dictan lo que consideran el primer curso online en Español sobre UX para Testers. Trabajó en la definición e implementación de procesos de testing en varios equipos y en capacitación sobre automatización de pruebas funcionales. Fue docente del Instituto de Computación de la Facultad de Ingeniería de la Universidad de la República durante casi 7 años, donde participó del dictado de cursos de testing y programación. Realizó los cursos Foundations y Bug Advocacy de la Association for Software Testing, el tutorial Agile Testing Essentials con Janet Gregory y Lisa Crispin y el curso Rapid Software Testing con Michael Bolton. También se ha certificado como Scrum Master y en ISTQB Foundation Level.

Información contacto:

- Twitter: [@claubs_uy](https://twitter.com/claubs_uy)
- LinkedIn: [www.linkedin.com/in/claudiabadell/](https://www.linkedin.com/in/claudiabadell/)
- Blog: [claudia-badell.com](https://claudia-badell.com)/ 

## Enlace al video

https://www.youtube.com/watch?v=wIP6Jx0T_zQ 

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/NorthemQuality/community-documentation/blob/master/CODIGO_CONDUCTA.md
[terms]: https://github.com/NorthemQuality/community-activities/blob/master/TERMS.md

**Comment by morvader** [comment]
Gracias por la propuesta @cbadell .

Fijamos tu charla para el 28 de Ferbero a las 19:00 (CET)

**Comment by morvader** [comment]
Muchas gracias por la charla @cbadell !

Aquí está el [vídeo ](https://www.youtube.com/watch?v=wIP6Jx0T_zQ)
